<template>
  <Loader v-if="isLoading" :is-fullsize="true" />
  <div class="confirm-container" v-if="isTFA">
    <Box>
      <template v-slot:header> Verify Your Identity </template>
      <template v-slot:body>
        <p class="text">To keep your account secure, we verify your identity</p>
        <br />
        <p class="text">Enter the code generated by your authenticator app.</p>
        <p class="text field mt-4">Verification code</p>
        <form @submit.prevent="handleSubmit">
          <div class="field">
            <div class="control">
              <input
                ref="codeRef"
                v-model.trim="code"
                class="input"
                placeholder="code" />
            </div>
          </div>
          <div class="field">
            <div class="columns">
              <div class="column">
                <button
                  type="submit"
                  class="button is-primary is-fullwidth is-outlined"
                  @click="router.push({ name: 'signin' })">
                  Cancel
                </button>
              </div>
              <div class="column">
                <button
                  type="submit"
                  class="button is-primary is-fullwidth"
                  :class="{ 'is-loading': isLoadingTFA }">
                  Send
                </button>
              </div>
            </div>
          </div>
        </form>
      </template>
    </Box>
  </div>
</template>
<script lang="ts" setup>
import { defineAsyncComponent, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';

import { storeToRefs } from 'pinia';

import { providers } from '../../../providers';
import { useAuthStore, useUserStore } from '../../../stores';
import { useLoading, useNotifications } from '../../common/composables';
import { IUser } from '../../../interfaces';

// COMPONENTES
const Box = defineAsyncComponent(
  () => import('../../common/components/ui/Box.vue'),
);
const Loader = defineAsyncComponent(
  () => import('../../common/components/Loader.vue'),
);

// STORES
const authStore = useAuthStore();
const userStore = useUserStore();
const { user } = storeToRefs(userStore);

// PROVIDERS
const { authService } = providers();

// COMPOSABLES
const route = useRoute();
const router = useRouter();
const { isLoading } = useLoading();
const notifications = useNotifications();

// VARIABLES
const isLoadingTFA = ref<boolean>(false);
const codeRef = ref<HTMLInputElement>();
const code = ref<string>('');
const isTFA = ref<boolean>(false);
const tfaData = ref({ login: '', avatar42: '' });

// FUNCIONES

const successAuth = (token: string, userAuth: IUser) => {
  authStore.signIn(token);
  userStore.setUser(userAuth);
  if (!user.value.username) router.push({ name: 'editProfile' });
  else router.push({ name: 'home' });
};

const activateTFA = (login: string, avatar42: string) => {
  tfaData.value.login = login;
  tfaData.value.avatar42 = avatar42;
  setTimeout(() => codeRef.value?.select(), 200);
};

const handleSubmit = async () => {
  try {
    isLoadingTFA.value = true;
    const response = await authService.confirmTFA({
      token: code.value,
      ...tfaData.value,
    });
    successAuth(response.token, response.user);
  } catch (error) {
    codeRef.value?.select();
    notifications.error("Can't auth user");
  } finally {
    isLoadingTFA.value = false;
  }
};

const signInApp = async (): Promise<void> => {
  try {
    isLoading.value = true;
    const response = await authService.signIn(route.query.code as string);
    if (response.twoFactorAuth) {
      isTFA.value = true;
      return activateTFA(response.login, response.avatar42);
    }
    successAuth(response.token, response.user);
  } catch (error) {
    notifications.error("Can't auth user");
    router.push({ name: 'signin' });
  } finally {
    isLoading.value = false;
  }
};

onMounted(() => {
  signInApp();
});
</script>
<style lang="scss" scoped>
.confirm-container {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>
