version: '3.7'

services:
  database:
    image: postgres:alpine3.17
    container_name: ${COMPOSE_PROJECT_NAME}_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_volume:/var/lib/postgresql
      - database_data_volume:/var/lib/postgresql/data
    ports:
      - "${BBDD_PORT}:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    depends_on:
      - database
    ports:
      - "${BACKEND_PORT}:3000"
    expose:
      - "3000"
    volumes:
      - ./backend:/app
      - backend_volume:/app/node_modules
    networks:
      - transcendence

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_web
    ports:
      - "${WEB_PORT}:5173"
    expose:
      - "5173"
    volumes:
      - ./web:/app
      - web_volume:/app/node_modules
    networks:
      - transcendence
 
volumes:
  database_volume:
    external: false
  database_data_volume:
    external: false
  backend_volume:
    external: false
  web_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './web/node_modules'

networks:
  transcendence:
    driver: bridge